global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "local"
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "us"
    static_configs:
      - targets: ["host.docker.internal:31883"]

  - job_name: "eu"
    static_configs:
      - targets: ["host.docker.internal:31884"]
