entryPoints:
  https:
    address: ":9445"
  metrics:
    address: ":9100"
  # web:
  #   address: ":9100" # HTTP entrypoint for non-TLS traffic (optional)

providers:
  file:
    # filename: dynamic.yml
    directory: "./dynamic"
    watch: true

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
