entryPoints:
  https:
    address: ":9445"
  metrics:
    address: ":9100"

providers:
  file:
    directory: "./dynamic"
    watch: true

log:
  level: INFO

api:
  dashboard: true
  insecure: true

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
